language: java
sudo: enabled
jdk:
- openjdk10
script:
- mvn install
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: PkfKPSsnlHkd5ddXskr3s4BvG5gabjj7slNfVSSbcrazjMJM/pGQI+dLpoo0+UDg73bm7kGS/tbz4FktbkvJxqNM/x/DzAG1+rjAfDwlmvFF13zkIwFrD+7OOfitPWdb8N6dPyZKJOZhJse8aSXX9we03epN3ewiUfPCAB4oCVUghDKJOAAt3TqBRcmpQBNDXN7pr8dL92ocV9fE6Oy3u8XdDvwIKiGQRzaWuPrMHDqq9gryFKErsHebGGZaLxPcr4+UDwLb5T/3koQoOVlQvwXTKz9LI1iTr3i6LcCFV11+iUBTwo9kSmUjlMphZcvYHtr+jV7w6D1ZS66iiZghB3W8taQ4HuCuckck/tzai+1jBj5GoLS2iRzBr6QqWeF8N9ahqPblZVkh1DUCH/j5o3a9DZvE7Qa6wFm+m/p4knua0LRbnkIRG4EXnrwgjIYUxX3Jb9QrIhFyFD+x5QSBE3hHoVy/zOBEz5YyBL3IoJQ2j6xqmnPsmgP1vdve3IpX1zzABNRLcSYL2FpGLnnE6Xu8RqeXVwBLGSPu49ol6ETKCrU1ckCz1NzYYVHmYjeOx8iGHd4ibBrjSfTf8iQT1l7tiQHLZuUZCRel0JTS89WKhAYvU7ivwBQ9mN7/48ffVLsZ89BdHM9lSkf942/mtZPuRy8L0locGe25nlBOUA0=
    # ^ THIS IS NOT A SECURITY RISK. I DID IT EXACTLY HOW TRAVIS WANTED ME TO DO IT. ^
  file: target/dhcpcord-0.1.jar
  on:
    repo: ARPTell/DHCPCord
